# -*- coding: utf-8 -*-
"""suc_GO_gemma3.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1AJ6sjX65KkbShL3AVWJyDRxAdB2HZUkJ
"""



"""### https://eli.thegreenplace.net/2024/gemma-ollama-and-langchaingo/"""

!curl -fsSL https://ollama.com/install.sh | sh

!nohup ollama serve &
!ollama pull gemma3

!ollama list

!wget https://go.dev/dl/go1.22.5.linux-amd64.tar.gz
!tar -C /usr/local -xzf go1.22.5.linux-amd64.tar.gz

# Commented out IPython magic to ensure Python compatibility.
!tar -C /usr/local -xzf go1.22.5.linux-amd64.tar.gz

# تحديث PATH بشكل مباشر للـ shell
# %env PATH=/usr/local/go/bin:$PATH

# الآن نتحقق
!go version

# Commented out IPython magic to ensure Python compatibility.
# %cd 1

!go mod init 1

!go get github.com/tmc/langchaingo/llms

!go get github.com/tmc/langchaingo/llms/ollama

!nohup ollama serve &
!go run 1.go

!go run 1.go

!go run 1.go --model gemma "what should be added to 91 to make -20?"

1.go


package main

import (
  "context"
  "fmt"
  "log"

  "github.com/tmc/langchaingo/llms"
  "github.com/tmc/langchaingo/llms/ollama"
)

func main() {
  llm, err := ollama.New(ollama.WithModel("gemma3"))
  if err != nil {
    log.Fatal(err)
  }

  query := "very briefly, tell me the difference between a comet and a meteor"

  ctx := context.Background()
  completion, err := llms.GenerateFromSinglePrompt(ctx, llm, query)
  if err != nil {
    log.Fatal(err)
  }

  fmt.Println("Response:\n", completion)
}

!go run 2.go --model gemma3 "what should be added to 91 to make -20?"

2.go




package main

import (
  "context"
  "flag"
  "fmt"
  "log"

  "github.com/tmc/langchaingo/llms"
  "github.com/tmc/langchaingo/llms/ollama"
)

func main() {
  modelName := flag.String("model", "", "gemma3")
  flag.Parse()

  llm, err := ollama.New(ollama.WithModel(*modelName))
  if err != nil {
    log.Fatal(err)
  }

  query := flag.Args()[0]
  ctx := context.Background()
  completion, err := llms.GenerateFromSinglePrompt(ctx, llm, query)
  if err != nil {
    log.Fatal(err)
  }

  fmt.Println("Response:\n", completion)
}