# -*- coding: utf-8 -*-
"""suc_GO_gemma3.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1AJ6sjX65KkbShL3AVWJyDRxAdB2HZUkJ
"""



!curl -fsSL https://ollama.com/install.sh | sh

!nohup ollama serve &
!ollama pull gemma3

!ollama list

!wget https://go.dev/dl/go1.22.5.linux-amd64.tar.gz
!tar -C /usr/local -xzf go1.22.5.linux-amd64.tar.gz

# Commented out IPython magic to ensure Python compatibility.
!tar -C /usr/local -xzf go1.22.5.linux-amd64.tar.gz

# تحديث PATH بشكل مباشر للـ shell
# %env PATH=/usr/local/go/bin:$PATH

# الآن نتحقق
!go version

# Commented out IPython magic to ensure Python compatibility.
# %cd 1

!go mod init 1

!go get github.com/tmc/langchaingo/llms

!go get github.com/tmc/langchaingo/llms/ollama

!nohup ollama serve &
!go run 1.go

!go run 1.go

