# -*- coding: utf-8 -*-
"""suc_gemma-3n-E4B-it_GGUF.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1qVEzQnYySQjiIsMxRyZLIJp1LYiCIwLG
"""







!wget https://huggingface.co/unsloth/gemma-3n-E4B-it-GGUF/resolve/main/gemma-3n-E4B-it-Q4_K_M.gguf

!export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:/content/build/bin && /content/build/bin/llama-cli -h

!wget https://github.com/ggml-org/llama.cpp/releases/download/b5797/llama-b5797-bin-ubuntu-x64.zip

!unzip llama-b5797-bin-ubuntu-x64.zip

!export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:/content/build/bin && /content/build/bin/llama-cli -h

!export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:/content/build/bin && /content/build/bin/llama-cli -m /content/gemma-3n-E4B-it-Q4_K_M.gguf -p "hi" -n 32