# -*- coding: utf-8 -*-
"""suc_function-calling-gemma3.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Qh1f4nJARHWsSmG8L9KwJ1cFwimcOvRj
"""





!git clone https://github.com/arjunprabhulal/function-calling-gemma3.git

# Commented out IPython magic to ensure Python compatibility.
# %cd function-calling-gemma3

!pip install -r requirements.txt

curl -fsSL https://ollama.com/install.sh | sh
nohup ollama serve &
ollama pull llama3:8b
ollama list

!curl -fsSL https://ollama.com/install.sh | sh

!nohup ollama serve &
!ollama pull gemma3

!ollama list

!cp .env.example .env

"""https://serper.dev/api-keys"""

# Commented out IPython magic to ensure Python compatibility.
!nohup ollama serve &
# %cd function-calling-gemma3
!python function-calling-gemma.py

kmnnmk212@gmail.com

"""https://github.com/arjunprabhulal/function-calling-gemma3"""

