# -*- coding: utf-8 -*-
"""suc_go.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1-s01Q5u15dDvdg3EXdCB_6Tm2vOuGs3H
"""





"""https://go.dev/dl




https://go.dev/doc/tutorial/getting-started

https://pkg.go.dev/testing

https://go.googlesource.com/proposal/+/master/design/14313-benchmark-format.md

https://github.com/golang/go/issues/14313

https://cs.opensource.google/go/go/+/refs/tags/go1.24.5:src/testing/run_example.go
"""

!wget https://go.dev/dl/go1.24.6.linux-amd64.tar.gz

!sudo rm -rf /usr/local/go && tar -C /usr/local -xzf go1.24.6.linux-amd64.tar.gz

!export PATH=$PATH:/usr/local/go/bin

!source $HOME/.profile

# Commented out IPython magic to ensure Python compatibility.
# %%bash
# /usr/local/go/bin/go

"""شغال"""

# Commented out IPython magic to ensure Python compatibility.
# %%bash
# export PATH=$PATH:/usr/local/go/bin
# go version

"""شغال"""

# Commented out IPython magic to ensure Python compatibility.
# %%bash
# /usr/local/go/bin/go version

# Commented out IPython magic to ensure Python compatibility.
# %%bash
# export PATH=$PATH:/usr/local/go/bin
# go version

!export PATH=$PATH:/usr/local/go/bin
!go version

!go version

!go run main.go

go

# Commented out IPython magic to ensure Python compatibility.
!mkdir hello
# %cd hello

# Commented out IPython magic to ensure Python compatibility.
# %%bash
# export PATH=$PATH:/usr/local/go/bin
# go mod init example/hello
#

# Commented out IPython magic to ensure Python compatibility.
# %%bash
# go run .

"""تشغيل الاصدار لجو من الترمنال"""

buildconstraint build constraints
        buildjson       build -json encoding
        buildmode       build modes
        c               calling between Go and C
        cache           build and test caching
        environment     environment variables
        filetype        file types
        goauth          GOAUTH environment variable
        go.mod          the go.mod file
        gopath          GOPATH environment variable
        goproxy         module proxy         buildconstraint build constraints
        buildjson       build -json encoding
        buildmode       build modes
        c               calling between Go and C
        cache           build and test caching
        environment     environment variables
        filetype        file types
        goauth          GOAUTH environment variable
        go.mod          the go.mod file
        gopath          GOPATH environment variable
        goproxy         module proxy ints
        buildjson       build -json encoding
        buildmode       build modes
        c               calling between Go and C
        cache           build and test caching
        environment     environment variables
        filetype        file types
        goauth          GOAUTH environment variable
        go.mod          the go.mod file
        gopath          GOPATH environment variable
        goproxy         module proxy protocol
        importpath      import path syntax
        modules         modules, module versions, and more
        module-auth     module authentication using go.sum
        packages        package lists and patterns
        private         configuration for downloading non-public code
        testflag        testing flags
        testfunc        testing functions
        vcs             controlling version control with GOVCS

Use "go help <topic>" for more information about that topic.

/content# go run .
no Go files in /content
/content# cd hello
/content/hello# go run .
Hello, World!
/content/hello# ^C
/content/hello#

"""نماذج للراج"""

https://github.com/wangle201210/go-rag/blob/main/server/manifest/config/config_demo.yaml


BAAI/bge-reranker-v2-m3
BAAI/bge-m3
Qwen/Qwen3-14B
Pro/deepseek-ai/DeepSeek-V3