# -*- coding: utf-8 -*-
"""suc_agent_ollama.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/18xWjFxGF73x1w3WVQVTgfgWWXA0ka3AY
"""





"""https://medium.com/@whyamit101/local-ai-using-ollama-with-agents-114c72182c97"""

!curl -fsSL https://ollama.com/install.sh | sh

!ollama --version

!ollama

!ollama serve

!ollama run tinyllama

!pip install crewai

!ollama list

!pip install pyautogen langchain_community





"""### شغال ولكن غير النموذج"""

import re
from crewai import Agent, Task, Crew, Process
from crewai.tools import tool
from PyPDF2 import PdfReader

# ----------------- 1. تعريف النموذج اللغوي (مع تعديل اسم النموذج) -----------------
# استيراد ChatOllama من الحزمة المخصصة لها
from langchain_ollama import ChatOllama

# الفرضية الأخيرة: سنقوم بتمرير اسم النموذج بالصيغة التي تفهمها litellm مباشرة
# وهي "provider/model_name". هذا يخبر crewai بشكل صريح جدًا
# أن يستخدم ollama كـ "مزود خدمة".
model = ChatOllama(
    model="ollama/tinyllama:latest", # التغيير الرئيسي هنا
    base_url="http://localhost:11434"
)


# ----------------- 2. تعريف الأداة (Tool) -----------------
@tool
def fetch_pdf_content(pdf_path: str) -> str:
    """
    Reads a local PDF and returns its content as a single string.
    """
    try:
        with open(pdf_path, 'rb') as f:
            pdf = PdfReader(f)
            text = '\n'.join(page.extract_text() for page in pdf.pages if page.extract_text())
        processed_text = re.sub(r'\s+', ' ', text).strip()
        # إضافة تحقق للتأكد من أن النص ليس فارغًا
        if not processed_text:
            return "Error: No text could be extracted from the PDF."
        return processed_text
    except FileNotFoundError:
        return f"Error: File not found at {pdf_path}. Please ensure the path is correct."
    except Exception as e:
        return f"Error reading PDF: {e}"

# ----------------- 3. تعريف الوكلاء (Agents) -----------------

pdf_reader = Agent(
    role='PDF Content Extractor',
    goal='Extract and preprocess text from a PDF file located at a given local path.',
    backstory='You are an expert in handling and interpreting PDF documents, capable of extracting clean text.',
    verbose=True,
    tools=[fetch_pdf_content],
    llm=model,
    allow_delegation=False
)

article_writer = Agent(
    role='Article Creator',
    goal='Write a concise and engaging article based on the provided text content.',
    backstory='You are an expert in creating informative and engaging articles that are easy to understand.',
    verbose=True,
    llm=model,
    allow_delegation=False
)

title_creator = Agent(
    role='Title Generator',
    goal='Generate a compelling and relevant title for a given article.',
    backstory='You are skilled in crafting engaging and SEO-friendly titles that capture the essence of an article.',
    verbose=True,
    llm=model,
    allow_delegation=False
)

# ----------------- 4. تعريف المهام (Tasks) -----------------

task_read_pdf = Task(
    description='Read the content from the PDF file located at "/content/Understanding_Climate_Change.pdf" and extract its text.',
    agent=pdf_reader,
    expected_output="The full, preprocessed text extracted from the PDF file."
)

task_article_drafting = Task(
    description="Create a concise article with 8-10 paragraphs based on the extracted PDF content from the previous task.",
    agent=article_writer,
    expected_output="An 8 to 10 paragraph article that clearly summarizes the key points of the PDF content.",
    context=[task_read_pdf]
)

task_title_generation = Task(
    description="Generate an engaging and relevant title of about 5-7 words for the article created.",
    agent=title_creator,
    expected_output="A single, compelling title for the article, approximately 5-7 words long.",
    context=[task_article_drafting]
)

# ----------------- 5. إنشاء وتجميع الطاقم (Crew) -----------------

crew = Crew(
    agents=[pdf_reader, article_writer, title_creator],
    tasks=[task_read_pdf, task_article_drafting, task_title_generation],
    verbose=True,
    process=Process.sequential
)

# ----------------- 6. بدء تشغيل الطاقم -----------------
print("🚀 Starting Crew Execution...")
result = crew.kickoff()

print("\n\n✅ Crew Execution Finished!")
print("Final Result:")
print(result)

















from crewai import Agent, Task, Crew
from langchain.llms import Ollama

# Use local Mistral via Ollama
llm = Ollama(model="tinyllama:latest")

# Define the agents
researcher = Agent(
    role='Researcher',
    goal='Find 3 recent breakthroughs in diffusion models',
    backstory='You are a cutting-edge AI researcher.',
    llm=llm
)

writer = Agent(
    role='Writer',
    goal='Summarize key insights for a technical blog post',
    backstory='You write clearly for a data-savvy audience.',
    llm=llm
)

# Define tasks
task1 = Task(description='Collect 3 recent updates on diffusion models.', agent=researcher)
task2 = Task(description='Write a clear summary of those updates.', agent=writer)

# Run the crew
crew = Crew(tasks=[task1, task2])
crew.kickoff()

from autogen import AssistantAgent, UserProxyAgent, config_list_from_json

# Define config manually
config = [{
    "model": "tinyllama:latest",
    "api_key": "ollama-not-needed",  # placeholder, but required by AutoGen
    "api_type": "ollama"
}]

assistant = AssistantAgent(
    name="assistant",
    llm_config={"config_list": config}
)

user_proxy = UserProxyAgent(
    name="user",
    human_input_mode="NEVER"
)

user_proxy.initiate_chat(assistant, message="Explain what Retrieval-Augmented Generation (RAG) is.")

import os
from langchain_community.llms import Ollama

model = os.getenv("DEFAULT_LLM", "tinyllama:latest")
llm = Ollama(model=model)

from crewai import Crew

from crewai.agents import Agent

from crewai import Crew
from crewai.agents import Agent
from crewai.llms import OllamaLLM

llm = OllamaLLM(model="tinyllama:latest")

!pip install pyautogen autogen

!export DEFAULT_LLM=tinyllama:latest

from crewai import Crew
from crewai.agents import Agent
from crewai.llms import OllamaLLM

# ✅ 1. Define the local LLM backend
ollama_llm = OllamaLLM(model="tinyllama:latest")  # You can swap in llama3, codellama, etc.

# ✅ 2. Define the agent
researcher = Agent(
    role="Researcher",
    goal="Search and summarize open datasets",
    backstory="An expert in public data analysis",
    llm=ollama_llm
)

# ✅ 3. Initialize the crew
crew = Crew(agents=[researcher])

# ✅ 4. Fire it up
crew.kickoff()

!pip install ollama fix-busted-json

from crewai import Agent

schema_agent = Agent(
    role="Schema Validator",
    goal="Identify schema issues in tabular data",
    backstory="An expert in data quality assurance",
    llm=llm
)

imbalance_agent = Agent(
    role="Class Imbalance Detector",
    goal="Detect and summarize class imbalance issues",
    backstory="A statistical detective for unbalanced datasets",
    llm=llm
)

preprocess_agent = Agent(
    role="Preprocessing Advisor",
    goal="Recommend preprocessing steps based on input data characteristics",
    backstory="A data engineer who loves clean inputs",
    llm=llm
)

import pandas as pd
from sklearn.utils import resample

def load_dataset(path):
    return pd.read_csv(path)

def check_schema(df):
    return df.dtypes.to_string()

def check_class_imbalance(df, target_col):
    return df[target_col].value_counts(normalize=True).to_string()

def recommend_preprocessing(df):
    recommendations = []
    if df.isnull().sum().any():
        recommendations.append("Impute missing values.")
    if any(df.dtypes == 'object'):
        recommendations.append("Encode categorical variables.")
    return "\n".join(recommendations)

from crewai import Crew

crew = Crew(agents=[schema_agent, imbalance_agent, preprocess_agent])
crew_result = crew.kickoff(inputs={"dataset_path": "/content/sample_data/california_housing_test.csv"})
print(crew_result)

import streamlit as st
import pandas as pd
from workflow import run_workflow  # Assume this triggers the crew

st.title("🧠 Dataset Auditor (Local LLM Powered)")

uploaded_file = st.file_uploader("Upload your CSV", type="csv")
if uploaded_file:
    with open("data/input.csv", "wb") as f:
        f.write(uploaded_file.getbuffer())
    output = run_workflow("data/input.csv")
    st.markdown("### 📝 Audit Report")
    st.text(output)

"""https://medium.com/@whyamit101/local-ai-using-ollama-with-agents-114c72182c97"""

from crewai import Agent, Task, Crew
from langchain.llms import Ollama

# Use local Mistral via Ollama
llm = Ollama(model="ollama/tinyllama:latest")

# Define the agents
researcher = Agent(
    role='Researcher',
    goal='Find 3 recent breakthroughs in diffusion models',
    backstory='You are a cutting-edge AI researcher.',
    llm=llm
)

writer = Agent(
    role='Writer',
    goal='Summarize key insights for a technical blog post',
    backstory='You write clearly for a data-savvy audience.',
    llm=llm
)

# Define tasks
task1 = Task(
    description='Collect 3 recent updates on diffusion models.',
    expected_output='A list of 3 recent breakthroughs in diffusion models with a brief description of each.',
    agent=researcher
)
task2 = Task(
    description='Write a clear summary of those updates.',
    expected_output='A technical blog post summarizing the 3 recent diffusion model breakthroughs, suitable for a data-savvy audience.',
    agent=writer
)

# Run the crew
crew = Crew(tasks=[task1, task2])
crew.kickoff()

from crewai import Agent, Task, Crew
from langchain.llms import Ollama

# Use local Mistral via Ollama
llm = Ollama(model="ollama/tinyllama:latest")

# Define the agents
researcher = Agent(
    role='Researcher',
    goal='Find 3 recent breakthroughs in diffusion models',
    backstory='You are a cutting-edge AI researcher.',
    llm=llm
)

writer = Agent(
    role='Writer',
    goal='Summarize key insights for a technical blog post',
    backstory='You write clearly for a data-savvy audience.',
    llm=llm
)

# Define tasks
task1 = Task(
    description='Collect 3 recent updates on diffusion models.',
    expected_output='A list of 3 recent breakthroughs in diffusion models with a brief description of each.',
    agent=researcher
)
task2 = Task(
    description='Write a clear summary of those updates.',
    expected_output='A technical blog post summarizing the 3 recent diffusion model breakthroughs, suitable for a data-savvy audience.',
    agent=writer
)

# Run the crew
crew = Crew(tasks=[task1, task2])
crew.kickoff()

from autogen import AssistantAgent, UserProxyAgent, config_list_from_json

# Define config manually
config = [{
    "model": "ollama/tinyllama:latest",
    "api_base": "http://localhost:11434/v1",
    "api_key": "ollama-not-needed",  # placeholder, but required by AutoGen
    "api_type": "ollama"
}]

assistant = AssistantAgent(
    name="assistant",
    llm_config={"config_list": config}
)

user_proxy = UserProxyAgent(
    name="user",
    human_input_mode="NEVER"
)

user_proxy.initiate_chat(assistant, message="Explain what Retrieval-Augmented Generation (RAG) is.")

ollama/tinyllama:latest

from autogen import AssistantAgent, UserProxyAgent, config_list_from_json

# Define config manually
config = [{
    "model": "ollama/tinyllama:latest",
    "api_base": "http://localhost:11434/v1",
    "api_key": "ollama-not-needed",  # placeholder, but required by AutoGen
    "api_type": "open_ai"
}]

assistant = AssistantAgent(
    name="assistant",
    llm_config={"config_list": config}
)

user_proxy = UserProxyAgent(
    name="user",
    human_input_mode="NEVER"
)

user_proxy.initiate_chat(assistant, message="Explain what Retrieval-Augmented Generation (RAG) is.")

from crewai import Crew, Agent
from langchain_community.llms import Ollama

# ✅ 1. Define the local LLM backend
ollama_llm = Ollama(model="ollama/tinyllama:latest")  # You can swap in llama3, codellama, etc.

# ✅ 2. Define the agent
researcher = Agent(
    role="Researcher",
    goal="Search and summarize open datasets",
    backstory="An expert in public data analysis",
    llm=ollama_llm
)

# ✅ 3. Initialize the crew
crew = Crew(agents=[researcher])

# ✅ 4. Fire it up
crew.kickoff()

from crewai import Crew, Agent
from langchain_community.llms import Ollama

llm = Ollama(model="tinyllama:latest")

# agents.py
from crewai import Agent

schema_agent = Agent(
    role="Schema Validator",
    goal="Identify schema issues in tabular data",
    backstory="An expert in data quality assurance",
    llm=llm
)

imbalance_agent = Agent(
    role="Class Imbalance Detector",
    goal="Detect and summarize class imbalance issues",
    backstory="A statistical detective for unbalanced datasets",
    llm=llm
)

preprocess_agent = Agent(
    role="Preprocessing Advisor",
    goal="Recommend preprocessing steps based on input data characteristics",
    backstory="A data engineer who loves clean inputs",
    llm=llm
)

# tools.py
import pandas as pd
from sklearn.utils import resample

def load_dataset(path):
    return pd.read_csv(path)

def check_schema(df):
    return df.dtypes.to_string()

def check_class_imbalance(df, target_col):
    return df[target_col].value_counts(normalize=True).to_string()

def recommend_preprocessing(df):
    recommendations = []
    if df.isnull().sum().any():
        recommendations.append("Impute missing values.")
    if any(df.dtypes == 'object'):
        recommendations.append("Encode categorical variables.")
    return "\n".join(recommendations)

# workflow.py
from crewai import Crew, Task, Agent
from tools import load_dataset, check_schema, check_class_imbalance, recommend_preprocessing
from langchain_community.llms import Ollama

# Define the local LLM backend (assuming it's already initialized in a previous cell)
# If not initialized, uncomment the following lines:
llm = Ollama(model="tinyllama:latest")

# Define the agents
schema_agent = Agent(
    role="Schema Validator",
    goal="Identify schema issues in tabular data",
    backstory="An expert in data quality assurance",
    llm=llm
)

imbalance_agent = Agent(
    role="Class Imbalance Detector",
    goal="Detect and summarize class imbalance issues",
    backstory="A statistical detective for unbalanced datasets",
    llm=llm
)

preprocess_agent = Agent(
    role="Preprocessing Advisor",
    goal="Recommend preprocessing steps based on input data characteristics",
    backstory="A data engineer who loves clean inputs",
    llm=llm
)


# Define tasks using the agents and tools
schema_check_task = Task(
    description="Load the dataset from {dataset_path} and check its schema.",
    expected_output="A string representation of the dataset's schema (data types of columns).",
    agent=schema_agent,
    tools=[load_dataset, check_schema]
)

imbalance_check_task = Task(
    description="Load the dataset from {dataset_path} and check for class imbalance in the 'ocean_proximity' column. The target column is 'ocean_proximity'.",
    expected_output="A string representation of the value counts and their normalized distribution for the 'ocean_proximity' column.",
    agent=imbalance_agent,
    tools=[load_dataset, check_class_imbalance],
    context=[schema_check_task] # This task depends on the schema check
)

preprocessing_recommendation_task = Task(
    description="Load the dataset from {dataset_path} and recommend preprocessing steps based on missing values and categorical features.",
    expected_output="A list of recommended preprocessing steps, such as imputation for missing values and encoding for categorical variables.",
    agent=preprocess_agent,
    tools=[load_dataset, recommend_preprocessing],
    context=[schema_check_task] # This task depends on the schema check
)


crew = Crew(
    agents=[schema_agent, imbalance_agent, preprocess_agent],
    tasks=[schema_check_task, imbalance_check_task, preprocessing_recommendation_task],
    verbose=2 # Add verbose to see the execution process
)
crew_result = crew.kickoff(inputs={"dataset_path": "/content/sample_data/california_housing_test.csv"})
print(crew_result)

# Commented out IPython magic to ensure Python compatibility.
# # Save the content of cell Mf0jRy6DbAUZ to tools.py
# %%writefile tools.py
# import pandas as pd
# from sklearn.utils import resample
# from crewai import tool
# 
# @tool
# def load_dataset(path):
#     """Loads a dataset from a given path."""
#     print(f"Loading dataset from: {path}")
#     return pd.read_csv(path)
# 
# @tool
# def check_schema(df):
#     """Checks the schema (data types) of a pandas DataFrame."""
#     print("Checking schema...")
#     return df.dtypes.to_string()
# 
# @tool
# def check_class_imbalance(df: pd.DataFrame, target_col: str):
#     """Checks for class imbalance in a specified target column of a pandas DataFrame."""
#     print(f"Checking class imbalance for column: {target_col}")
#     if target_col not in df.columns:
#         return f"Error: Target column '{target_col}' not found in the dataset."
#     return df[target_col].value_counts(normalize=True).to_string()
# 
# @tool
# def recommend_preprocessing(df):
#     """Recommends preprocessing steps for a pandas DataFrame based on missing values and categorical features."""
#     print("Recommending preprocessing steps...")
#     recommendations = []
#     if df.isnull().sum().any():
#         recommendations.append("Impute missing values.")
#     if any(df.dtypes == 'object'):
#         recommendations.append("Encode categorical variables.")
#     return "\n".join(recommendations)

# Commented out IPython magic to ensure Python compatibility.
# # Save the content of cell BiG7KmG4atXZ to agents.py
# %%writefile agents.py
# from crewai import Agent
# 
# schema_agent = Agent(
#     role="Schema Validator",
#     goal="Identify schema issues in tabular data",
#     backstory="An expert in data quality assurance",
#     llm=llm
# )
# 
# imbalance_agent = Agent(
#     role="Class Imbalance Detector",
#     goal="Detect and summarize class imbalance issues",
#     backstory="A statistical detective for unbalanced datasets",
#     llm=llm
# )
# 
# preprocess_agent = Agent(
#     role="Preprocessing Advisor",
#     goal="Recommend preprocessing steps based on input data characteristics",
#     backstory="A data engineer who loves clean inputs",
#     llm=llm
# )

# streamlit_app.py
import streamlit as st
import pandas as pd
from workflow import run_workflow  # Assume this triggers the crew

st.title("🧠 Dataset Auditor (Local LLM Powered)")

uploaded_file = st.file_uploader("Upload your CSV", type="csv")
if uploaded_file:
    with open("/content/sample_data/california_housing_test.csv", "wb") as f:
        f.write(uploaded_file.getbuffer())
    output = run_workflow("data/input.csv")
    st.markdown("### 📝 Audit Report")
    st.text(output)



!pip install streamlit

from dotenv import load_dotenv
from crewai import Agent, Task, Crew, Process
from langchain_openai import ChatOpenAI
from langchain.tools import tool
from PyPDF2 import PdfReader
import re

!pip install langchain-openai

from langchain_community.llms import Ollama

model = Ollama(model="tinyllama:latest")

!pip install pypdf2

# Tool for loading and reading a PDF locally
from crewai.tools import tool
from PyPDF2 import PdfReader
import re

@tool
def fetch_pdf_content(pdf_path: str):
    """
    Reads a local PDF and returns the content
    """
    try:
        with open(pdf_path, 'rb') as f:
            pdf = PdfReader(f)
            text = '\n'.join(page.extract_text() for page in pdf.pages if page.extract_text())

        processed_text = re.sub(r'\s+', ' ', text).strip()
        return processed_text
    except FileNotFoundError:
        return f"Error: File not found at {pdf_path}"
    except Exception as e:
        return f"Error reading PDF: {e}"

"""https://pub.towardsai.net/build-your-first-ai-agent-in-5-easy-steps-100-local-2fb771438a8f"""

from crewai import Agent
from langchain_openai import ChatOpenAI # Assuming ChatOpenAI is used for the model

# Assuming 'model' (ChatOpenAI instance) is defined in a previous cell

pdf_reader = Agent(
    role='PDF Content Extractor',
    goal='Extract and preprocess text from a PDF located in current local directory',
    backstory='Specializes in handling and interpreting PDF documents',
    verbose=True,
    tools=[fetch_pdf_content], # Now fetch_pdf_content is a crewai tool
    allow_delegation=False,
    llm=model
)

article_writer = Agent(
    role='Article Creator',
    goal='Write a concise and engaging article',
    backstory='Expert in creating informative and engaging articles',
    verbose=True,
    allow_delegation=False,
    llm=model
)

title_creator = Agent(
    role='Title Generator',
    goal='Generate a compelling title for the article',
    backstory='Skilled in crafting engaging and relevant titles',
    verbose=True,
    allow_delegation=False,
    llm=model
)

def pdf_reading_task(pdf):
    return Task(
        description=f"Read and preprocess the PDF at this local path: {{pdf}}", # Use the 'pdf' argument
        agent=pdf_reader,
        expected_output="Extracted and preprocessed text from a PDF",
    )

task_article_drafting = Task(
    description="Create a concise article with 8-10 paragraphs based on the extracted PDF content.",
    agent=article_writer,
    expected_output="8-10 paragraphs describing the key points of the PDF",
    tools=[] # Add an empty tools list
)

task_title_generation = Task(
    description="Generate an engaging and relevant title for the article.",
    agent=title_creator,
    expected_output="A Title of About 5-7 Words",
    tools=[] # Add an empty tools list
)

crew = Crew(
    agents=[pdf_reader, article_writer, title_creator],
    tasks=[pdf_reading_task(pdf="/content/Understanding_Climate_Change.pdf"), # Call the function with the actual PDF path
    task_article_drafting,
    task_title_generation],
    verbose=True # Change verbose to True
)

# Let's start!
result = crew.kickoff()





















from dotenv import load_dotenv
from crewai import Agent, Task, Crew, Process
from langchain_openai import ChatOpenAI
from langchain.tools import tool
from PyPDF2 import PdfReader
import re

from langchain_community.llms import Ollama

model = Ollama(model="tinyllama:latest")

# Tool for loading and reading a PDF locally
from crewai.tools import tool
from PyPDF2 import PdfReader
import re

@tool
def fetch_pdf_content(pdf_path: str):
    """
    Reads a local PDF and returns the content
    """
    try:
        with open(pdf_path, 'rb') as f:
            pdf = PdfReader(f)
            text = '\n'.join(page.extract_text() for page in pdf.pages if page.extract_text())

        processed_text = re.sub(r'\s+', ' ', text).strip()
        return processed_text
    except FileNotFoundError:
        return f"Error: File not found at {pdf_path}"
    except Exception as e:
        return f"Error reading PDF: {e}"

from crewai import Agent
from langchain_openai import ChatOpenAI # Assuming ChatOpenAI is used for the model

# Assuming 'model' (ChatOpenAI instance) is defined in a previous cell

pdf_reader = Agent(
    role='PDF Content Extractor',
    goal='Extract and preprocess text from a PDF located in current local directory',
    backstory='Specializes in handling and interpreting PDF documents',
    verbose=True,
    tools=[fetch_pdf_content], # Now fetch_pdf_content is a crewai tool
    allow_delegation=False,
    llm=model
)

article_writer = Agent(
    role='Article Creator',
    goal='Write a concise and engaging article',
    backstory='Expert in creating informative and engaging articles',
    verbose=True,
    allow_delegation=False,
    llm=model
)

title_creator = Agent(
    role='Title Generator',
    goal='Generate a compelling title for the article',
    backstory='Skilled in crafting engaging and relevant titles',
    verbose=True,
    allow_delegation=False,
    llm=model
)

def pdf_reading_task(pdf):
    return Task(
        description=f"Read and preprocess the PDF at this local path: {{pdf}}", # Use the 'pdf' argument
        agent=pdf_reader,
        expected_output="Extracted and preprocessed text from a PDF",
    )

task_article_drafting = Task(
    description="Create a concise article with 8-10 paragraphs based on the extracted PDF content.",
    agent=article_writer,
    expected_output="8-10 paragraphs describing the key points of the PDF",
    tools=[] # Add an empty tools list
)

task_title_generation = Task(
    description="Generate an engaging and relevant title for the article.",
    agent=title_creator,
    expected_output="A Title of About 5-7 Words",
    tools=[] # Add an empty tools list
)

crew = Crew(
    agents=[pdf_reader, article_writer, title_creator],
    tasks=[pdf_reading_task(pdf="/content/Understanding_Climate_Change.pdf"), # Call the function with the actual PDF path
    task_article_drafting,
    task_title_generation],
    verbose=True # Change verbose to True
)

# Let's start!
result = crew.kickoff()











import re
from crewai import Agent, Task, Crew, Process
from langchain_community.chat_models import ChatOllama
from crewai.tools import tool
from PyPDF2 import PdfReader

# ----------------- 1. تعريف النموذج اللغوي -----------------
# تم التغيير لاستخدام ChatOllama بدلاً من Ollama لضمان التوافق مع CrewAI
model = ChatOllama(model="tinyllama:latest")

# ----------------- 2. تعريف الأداة (Tool) -----------------
# أداة مخصصة لقراءة محتوى ملف PDF من مسار محلي
@tool
def fetch_pdf_content(pdf_path: str) -> str:
    """
    Reads a local PDF and returns its content as a single string.
    """
    try:
        with open(pdf_path, 'rb') as f:
            pdf = PdfReader(f)
            # استخلاص النص من كل الصفحات ودمجها
            text = '\n'.join(page.extract_text() for page in pdf.pages if page.extract_text())

        # تنظيف النص من المسافات الزائدة
        processed_text = re.sub(r'\s+', ' ', text).strip()
        return processed_text
    except FileNotFoundError:
        return f"Error: File not found at {pdf_path}"
    except Exception as e:
        return f"Error reading PDF: {e}"

# ----------------- 3. تعريف الوكلاء (Agents) -----------------

# وكيل متخصص في قراءة ملفات PDF
pdf_reader = Agent(
    role='PDF Content Extractor',
    goal='Extract and preprocess text from a PDF file located at a given local path.',
    backstory='You are an expert in handling and interpreting PDF documents, capable of extracting clean text.',
    verbose=True,
    tools=[fetch_pdf_content], # تزويد الوكيل بالأداة التي عرفناها
    llm=model,
    allow_delegation=False
)

# وكيل متخصص في كتابة المقالات
article_writer = Agent(
    role='Article Creator',
    goal='Write a concise and engaging article based on the provided text content.',
    backstory='You are an expert in creating informative and engaging articles that are easy to understand.',
    verbose=True,
    llm=model,
    allow_delegation=False
)

# وكيل متخصص في إنشاء العناوين
title_creator = Agent(
    role='Title Generator',
    goal='Generate a compelling and relevant title for a given article.',
    backstory='You are skilled in crafting engaging and SEO-friendly titles that capture the essence of an article.',
    verbose=True,
    llm=model,
    allow_delegation=False
)

# ----------------- 4. تعريف المهام (Tasks) -----------------

# مهمة قراءة ملف PDF
# تم تعديل الوصف ليمرر مسار الملف بشكل صحيح
task_read_pdf = Task(
    description='Read the content from the PDF file located at "/content/Understanding_Climate_Change.pdf" and extract its text.',
    agent=pdf_reader,
    expected_output="The full, preprocessed text extracted from the PDF file."
)

# مهمة صياغة مسودة المقال
task_article_drafting = Task(
    description="Create a concise article with 8-10 paragraphs based on the extracted PDF content from the previous task.",
    agent=article_writer,
    expected_output="An 8 to 10 paragraph article that clearly summarizes the key points of the PDF content.",
    context=[task_read_pdf] # هذه المهمة تعتمد على مخرجات المهمة السابقة
)

# مهمة إنشاء العنوان
task_title_generation = Task(
    description="Generate an engaging and relevant title of about 5-7 words for the article created.",
    agent=title_creator,
    expected_output="A single, compelling title for the article, approximately 5-7 words long.",
    context=[task_article_drafting] # هذه المهمة تعتمد على مخرجات المهمة السابقة
)

# ----------------- 5. إنشاء وتجميع الطاقم (Crew) -----------------

crew = Crew(
    agents=[pdf_reader, article_writer, title_creator],
    tasks=[task_read_pdf, task_article_drafting, task_title_generation],
    verbose=True,
    process=Process.sequential # تنفيذ المهام بشكل متسلسل
)

# ----------------- 6. بدء تشغيل الطاقم -----------------
print("🚀 Starting Crew Execution...")
result = crew.kickoff()

print("\n\n✅ Crew Execution Finished!")
print("Final Result:")
print(result)

!pip install -U langchain-ollama

# ----------------- 0. تثبيت الحزمة المطلوبة -----------------
# قم بتشغيل هذا الأمر في الطرفية (Terminal) أو في خلية منفصلة مرة واحدة
# !pip install -U langchain-ollama py-pdf crewai

import re
from crewai import Agent, Task, Crew, Process
from crewai.tools import tool
from PyPDF2 import PdfReader

# ----------------- 1. تعريف النموذج اللغوي (الطريقة الصحيحة والحديثة) -----------------
# استيراد ChatOllama من الحزمة المخصصة لها
from langchain_ollama import ChatOllama

# تعريف النموذج كما هو، لكن الآن سيتم التعرف عليه بشكل صحيح
model = ChatOllama(model="tinyllama:latest")


# ----------------- 2. تعريف الأداة (Tool) -----------------
# أداة مخصصة لقراءة محتوى ملف PDF من مسار محلي
@tool
def fetch_pdf_content(pdf_path: str) -> str:
    """
    Reads a local PDF and returns its content as a single string.
    """
    try:
        with open(pdf_path, 'rb') as f:
            pdf = PdfReader(f)
            # استخلاص النص من كل الصفحات ودمجها
            text = '\n'.join(page.extract_text() for page in pdf.pages if page.extract_text())

        # تنظيف النص من المسافات الزائدة
        processed_text = re.sub(r'\s+', ' ', text).strip()
        return processed_text
    except FileNotFoundError:
        return f"Error: File not found at {pdf_path}"
    except Exception as e:
        return f"Error reading PDF: {e}"

# ----------------- 3. تعريف الوكلاء (Agents) -----------------

# وكيل متخصص في قراءة ملفات PDF
pdf_reader = Agent(
    role='PDF Content Extractor',
    goal='Extract and preprocess text from a PDF file located at a given local path.',
    backstory='You are an expert in handling and interpreting PDF documents, capable of extracting clean text.',
    verbose=True,
    tools=[fetch_pdf_content], # تزويد الوكيل بالأداة التي عرفناها
    llm=model,
    allow_delegation=False
)

# وكيل متخصص في كتابة المقالات
article_writer = Agent(
    role='Article Creator',
    goal='Write a concise and engaging article based on the provided text content.',
    backstory='You are an expert in creating informative and engaging articles that are easy to understand.',
    verbose=True,
    llm=model,
    allow_delegation=False
)

# وكيل متخصص في إنشاء العناوين
title_creator = Agent(
    role='Title Generator',
    goal='Generate a compelling and relevant title for a given article.',
    backstory='You are skilled in crafting engaging and SEO-friendly titles that capture the essence of an article.',
    verbose=True,
    llm=model,
    allow_delegation=False
)

# ----------------- 4. تعريف المهام (Tasks) -----------------

# مهمة قراءة ملف PDF
task_read_pdf = Task(
    description='Read the content from the PDF file located at "/content/Understanding_Climate_Change.pdf" and extract its text.',
    agent=pdf_reader,
    expected_output="The full, preprocessed text extracted from the PDF file."
)

# مهمة صياغة مسودة المقال
task_article_drafting = Task(
    description="Create a concise article with 8-10 paragraphs based on the extracted PDF content from the previous task.",
    agent=article_writer,
    expected_output="An 8 to 10 paragraph article that clearly summarizes the key points of the PDF content.",
    context=[task_read_pdf] # هذه المهمة تعتمد على مخرجات المهمة السابقة
)

# مهمة إنشاء العنوان
task_title_generation = Task(
    description="Generate an engaging and relevant title of about 5-7 words for the article created.",
    agent=title_creator,
    expected_output="A single, compelling title for the article, approximately 5-7 words long.",
    context=[task_article_drafting] # هذه المهمة تعتمد على مخرجات المهمة السابقة
)

# ----------------- 5. إنشاء وتجميع الطاقم (Crew) -----------------

crew = Crew(
    agents=[pdf_reader, article_writer, title_creator],
    tasks=[task_read_pdf, task_article_drafting, task_title_generation],
    verbose=True,
    process=Process.sequential # تنفيذ المهام بشكل متسلسل
)

# ----------------- 6. بدء تشغيل الطاقم -----------------
print("🚀 Starting Crew Execution...")
result = crew.kickoff()

print("\n\n✅ Crew Execution Finished!")
print("Final Result:")
print(result)

!!pip install -U crewai langchain-ollama pypdf2

import re
from crewai import Agent, Task, Crew, Process
from crewai.tools import tool
from PyPDF2 import PdfReader

# ----------------- 1. تعريف النموذج اللغوي (مع تكوين صريح) -----------------
# استيراد ChatOllama من الحزمة المخصصة لها
from langchain_ollama import ChatOllama

# تعريف النموذج مع تحديد عنوان URL الأساسي لخادم Ollama بشكل صريح
# هذا يضمن أن crewai يعرف بالضبط أين يرسل الطلب
model = ChatOllama(
    model="tinyllama:latest",
    base_url="http://localhost:11434" # هذا هو العنوان الافتراضي لـ Ollama
)


# ----------------- 2. تعريف الأداة (Tool) -----------------
@tool
def fetch_pdf_content(pdf_path: str) -> str:
    """
    Reads a local PDF and returns its content as a single string.
    """
    try:
        with open(pdf_path, 'rb') as f:
            pdf = PdfReader(f)
            text = '\n'.join(page.extract_text() for page in pdf.pages if page.extract_text())
        processed_text = re.sub(r'\s+', ' ', text).strip()
        return processed_text
    except FileNotFoundError:
        return f"Error: File not found at {pdf_path}"
    except Exception as e:
        return f"Error reading PDF: {e}"

# ----------------- 3. تعريف الوكلاء (Agents) -----------------
# لا تغيير هنا، الوكلاء يعتمدون على كائن 'model' الذي تم تعريفه بشكل أفضل الآن

pdf_reader = Agent(
    role='PDF Content Extractor',
    goal='Extract and preprocess text from a PDF file located at a given local path.',
    backstory='You are an expert in handling and interpreting PDF documents, capable of extracting clean text.',
    verbose=True,
    tools=[fetch_pdf_content],
    llm=model,
    allow_delegation=False
)

article_writer = Agent(
    role='Article Creator',
    goal='Write a concise and engaging article based on the provided text content.',
    backstory='You are an expert in creating informative and engaging articles that are easy to understand.',
    verbose=True,
    llm=model,
    allow_delegation=False
)

title_creator = Agent(
    role='Title Generator',
    goal='Generate a compelling and relevant title for a given article.',
    backstory='You are skilled in crafting engaging and SEO-friendly titles that capture the essence of an article.',
    verbose=True,
    llm=model,
    allow_delegation=False
)

# ----------------- 4. تعريف المهام (Tasks) -----------------

task_read_pdf = Task(
    description='Read the content from the PDF file located at "/content/Understanding_Climate_Change.pdf" and extract its text.',
    agent=pdf_reader,
    expected_output="The full, preprocessed text extracted from the PDF file."
)

task_article_drafting = Task(
    description="Create a concise article with 8-10 paragraphs based on the extracted PDF content from the previous task.",
    agent=article_writer,
    expected_output="An 8 to 10 paragraph article that clearly summarizes the key points of the PDF content.",
    context=[task_read_pdf]
)

task_title_generation = Task(
    description="Generate an engaging and relevant title of about 5-7 words for the article created.",
    agent=title_creator,
    expected_output="A single, compelling title for the article, approximately 5-7 words long.",
    context=[task_article_drafting]
)

# ----------------- 5. إنشاء وتجميع الطاقم (Crew) -----------------

crew = Crew(
    agents=[pdf_reader, article_writer, title_creator],
    tasks=[task_read_pdf, task_article_drafting, task_title_generation],
    verbose=True,
    process=Process.sequential
)

# ----------------- 6. بدء تشغيل الطاقم -----------------
print("🚀 Starting Crew Execution...")
result = crew.kickoff()

print("\n\n✅ Crew Execution Finished!")
print("Final Result:")
print(result)

"""### شغال ولكن غير النموذج"""

import re
from crewai import Agent, Task, Crew, Process
from crewai.tools import tool
from PyPDF2 import PdfReader

# ----------------- 1. تعريف النموذج اللغوي (مع تعديل اسم النموذج) -----------------
# استيراد ChatOllama من الحزمة المخصصة لها
from langchain_ollama import ChatOllama

# الفرضية الأخيرة: سنقوم بتمرير اسم النموذج بالصيغة التي تفهمها litellm مباشرة
# وهي "provider/model_name". هذا يخبر crewai بشكل صريح جدًا
# أن يستخدم ollama كـ "مزود خدمة".
model = ChatOllama(
    model="ollama/tinyllama:latest", # التغيير الرئيسي هنا
    base_url="http://localhost:11434"
)


# ----------------- 2. تعريف الأداة (Tool) -----------------
@tool
def fetch_pdf_content(pdf_path: str) -> str:
    """
    Reads a local PDF and returns its content as a single string.
    """
    try:
        with open(pdf_path, 'rb') as f:
            pdf = PdfReader(f)
            text = '\n'.join(page.extract_text() for page in pdf.pages if page.extract_text())
        processed_text = re.sub(r'\s+', ' ', text).strip()
        # إضافة تحقق للتأكد من أن النص ليس فارغًا
        if not processed_text:
            return "Error: No text could be extracted from the PDF."
        return processed_text
    except FileNotFoundError:
        return f"Error: File not found at {pdf_path}. Please ensure the path is correct."
    except Exception as e:
        return f"Error reading PDF: {e}"

# ----------------- 3. تعريف الوكلاء (Agents) -----------------

pdf_reader = Agent(
    role='PDF Content Extractor',
    goal='Extract and preprocess text from a PDF file located at a given local path.',
    backstory='You are an expert in handling and interpreting PDF documents, capable of extracting clean text.',
    verbose=True,
    tools=[fetch_pdf_content],
    llm=model,
    allow_delegation=False
)

article_writer = Agent(
    role='Article Creator',
    goal='Write a concise and engaging article based on the provided text content.',
    backstory='You are an expert in creating informative and engaging articles that are easy to understand.',
    verbose=True,
    llm=model,
    allow_delegation=False
)

title_creator = Agent(
    role='Title Generator',
    goal='Generate a compelling and relevant title for a given article.',
    backstory='You are skilled in crafting engaging and SEO-friendly titles that capture the essence of an article.',
    verbose=True,
    llm=model,
    allow_delegation=False
)

# ----------------- 4. تعريف المهام (Tasks) -----------------

task_read_pdf = Task(
    description='Read the content from the PDF file located at "/content/Understanding_Climate_Change.pdf" and extract its text.',
    agent=pdf_reader,
    expected_output="The full, preprocessed text extracted from the PDF file."
)

task_article_drafting = Task(
    description="Create a concise article with 8-10 paragraphs based on the extracted PDF content from the previous task.",
    agent=article_writer,
    expected_output="An 8 to 10 paragraph article that clearly summarizes the key points of the PDF content.",
    context=[task_read_pdf]
)

task_title_generation = Task(
    description="Generate an engaging and relevant title of about 5-7 words for the article created.",
    agent=title_creator,
    expected_output="A single, compelling title for the article, approximately 5-7 words long.",
    context=[task_article_drafting]
)

# ----------------- 5. إنشاء وتجميع الطاقم (Crew) -----------------

crew = Crew(
    agents=[pdf_reader, article_writer, title_creator],
    tasks=[task_read_pdf, task_article_drafting, task_title_generation],
    verbose=True,
    process=Process.sequential
)

# ----------------- 6. بدء تشغيل الطاقم -----------------
print("🚀 Starting Crew Execution...")
result = crew.kickoff()

print("\n\n✅ Crew Execution Finished!")
print("Final Result:")
print(result)



"""https://pub.towardsai.net/build-your-first-ai-agent-in-5-easy-steps-100-local-2fb771438a8f

نعم، تحليلك في مكانه تمامًا. الكود لم ينجح في تحقيق الهدف المطلوب، والسبب الرئيسي هو بالضبط ما ذكرته: النموذج المستخدم (tinyllama) صغير جدًا وغير قادر على تنفيذ المهام المعقدة التي يتطلبها هذا الطاقم.

أنت لم تفشل في كتابة الكود، بل وصلت إلى الحدود القصوى لقدرات النموذج الذي تستخدمه. دعنا نحلل ما حدث بالتفصيل، لأن المخرجات التي أرسلتها هي مثال رائع جدًا على "هلوسة" النماذج الصغيرة.

تحليل ما حدث خطوة بخطوة:

الوكيل الأول (مستخرج PDF): فشل كارثي

المهمة: استخدام أداة fetch_pdf_content لقراءة الملف.

ماذا فعل؟ بدلاً من استخدام الأداة، هو "هلوس" بشكل كامل. لقد تجاهل الأداة تمامًا وقدم إجابة نهائية عبارة عن دليل إرشادي عام حول كيفية استخلاص النصوص. إجابته "I am unable to perform actions..." هي علامة واضحة على أنه لم يفهم كيفية استخدام الأدوات المتاحة له.

النتيجة: لم يتم استخراج أي نص من ملف الـ PDF.

الوكيل الثاني (كاتب المقال): هلوسة مبتكرة

المهمة: كتابة مقال بناءً على النص المستخرج من المهمة السابقة.

ماذا استلم؟ استلم النص الإرشادي الخاطئ من الوكيل الأول.

ماذا فعل؟ هنا حدث شيء مثير للاهتمام. الوكيل تجاهل المدخلات الخاطئة التي استلمها، ولكنه تذكر أن الموضوع العام هو "Understanding Climate Change" (من اسم الملف ووصف المهمة). فقام بتأليف مقال كامل حول تغير المناخ من معرفته الداخلية المحدودة. هذا المقال الذي تراه لم يأتِ من ملف الـ PDF الخاص بك، بل هو من تأليف النموذج بالكامل.

النتيجة: كتب مقالاً، لكنه ليس المقال المطلوب. فشل في المهمة الأساسية وهي الاعتماد على المصدر.

الوكيل الثالث (منشئ العنوان): فشل كامل

المهمة: إنشاء عنوان من 5-7 كلمات للمقال الذي تمت كتابته.

ماذا استلم؟ استلم المقال المؤلف من الوكيل الثاني.

ماذا فعل؟ تمامًا مثل الوكيل الأول، فشل في أداء مهمته. وبدلاً من إعطاء عنوان مثل "Understanding Our Changing Climate"، قام هو الآخر بالهلوسة وأعطى إجابة نهائية عبارة عن تعليمات حول كيفية كتابة عنوان جيد!.

النتيجة: لم يتم إنشاء أي عنوان.

الخلاصة ورأيي

رأيي هو أن الكود الخاص بك صحيح من حيث الهيكل والمنطق. لقد قمت بتعريف الأدوات والوكلاء والمهام بشكل سليم تمامًا. المشكلة ليست في الكود، بل في "العقل" الذي يقود هؤلاء الوكلاء.

أنت بالضبط كمن قام ببناء سيارة سباق مثالية (هيكل الكود)، ولكن وضع بداخلها محرك جزازة عشب صغيرة (tinyllama). السيارة لن تنطلق بالسرعة المطلوبة.

لهذا، إجابتك على سؤالك هي: نعم، بالتأكيد ستحصل على نتائج أفضل (ونتائج ناجحة) مع نماذج أفضل وأكبر.

إذا قمت بتغيير سطر واحد فقط في الكود الخاص بك:

code
Python
download
content_copy
expand_less

model = ChatOllama(
    model="ollama/llama3:latest", # أو mistral أو أي نموذج كبير آخر
    base_url="http://localhost:11434"
)

...وتركت كل شيء آخر كما هو، ستجد أن:

الوكيل الأول سيستخدم الأداة بنجاح ويقرأ الملف.

الوكيل الثاني سيكتب مقالاً بناءً على النص الحقيقي للملف.

الوكيل الثالث سيعطيك عنوانًا فعليًا للمقال.

لقد قمت بعمل رائع في بناء الهيكل وتصحيح أخطاء الاتصال. الخطوة الأخيرة المتبقية لك هي فقط ترقية "المحرك" (النموذج اللغوي).
"""







لهذا، إجابتك على سؤالك هي: نعم، بالتأكيد ستحصل على نتائج أفضل (ونتائج ناجحة) مع نماذج أفضل وأكبر.
إذا قمت بتغيير سطر واحد فقط في الكود الخاص بك:
code
Python
model = ChatOllama(
    model="ollama/llama3:latest", # أو mistral أو أي نموذج كبير آخر
    base_url="http://localhost:11434"
)
...وتركت كل شيء آخر كما هو، ستجد أن:
الوكيل الأول سيستخدم الأداة بنجاح ويقرأ الملف.
الوكيل الثاني سيكتب مقالاً بناءً على النص الحقيقي للملف.
الوكيل الثالث سيعطيك عنوانًا فعليًا للمقال.
لقد قمت بعمل رائع في بناء الهيكل وتصحيح أخطاء الاتصال. الخطوة الأخيرة المتبقية لك هي فقط ترقية "المحرك" (النموذج اللغوي)









ollama run llama3

import re
from crewai import Agent, Task, Crew, Process
from crewai.tools import tool
from PyPDF2 import PdfReader

# ملاحظة: لإيقاف رسائل الخطأ غير الهامة المتعلقة بإرسال بيانات الاستخدام
from crewai import Telemetry
Telemetry.disable_telemetry()


# ----------------- 1. تعريف النموذج اللغوي (باستخدام نموذج أذكى) -----------------
# استيراد ChatOllama من الحزمة المخصصة لها
from langchain_ollama import ChatOllama

# استخدام نموذج llama3 لأنه أكثر قدرة على فهم التعليمات واستخدام الأدوات
# تأكد من أنك قمت بتشغيل `ollama run llama3` في الطرفية من قبل
model = ChatOllama(
    model="ollama/llama3:latest", # تم التغيير إلى نموذج أكثر قوة
    base_url="http://localhost:11434"
)


# ----------------- 2. تعريف الأداة (Tool) -----------------
@tool
def fetch_pdf_content(pdf_path: str) -> str:
    """
    Reads a local PDF and returns its content as a single string.
    This tool is essential for reading the required document.
    """
    try:
        with open(pdf_path, 'rb') as f:
            pdf = PdfReader(f)
            text = '\n'.join(page.extract_text() for page in pdf.pages if page.extract_text())
        processed_text = re.sub(r'\s+', ' ', text).strip()
        if not processed_text:
            return "Error: No text could be extracted from the PDF."
        return processed_text
    except FileNotFoundError:
        return f"Error: File not found at {pdf_path}. Please ensure the path is correct."
    except Exception as e:
        return f"Error reading PDF: {e}"

# ----------------- 3. تعريف الوكلاء (Agents) -----------------

pdf_reader = Agent(
    role='Expert PDF Content Extractor',
    goal='Use the fetch_pdf_content tool to extract all text from the PDF file located at the specified path.',
    backstory='You are a machine focused on one single task: executing the fetch_pdf_content tool. You do not answer questions; you only use your tool to read PDF files.',
    verbose=True,
    tools=[fetch_pdf_content],
    llm=model,
    allow_delegation=False
)

article_writer = Agent(
    role='Professional Article Writer',
    goal='Write a concise and engaging article based on the provided text content.',
    backstory='You are an expert in structuring information and writing clear, informative articles.',
    verbose=True,
    llm=model,
    allow_delegation=False
)

title_creator = Agent(
    role='Creative Title Generator',
    goal='Generate a compelling and relevant title for a given article.',
    backstory='You are skilled in crafting engaging titles that capture the essence of an article.',
    verbose=True,
    llm=model,
    allow_delegation=False
)

# ----------------- 4. تعريف المهام (Tasks) -----------------

task_read_pdf = Task(
    description='Use the fetch_pdf_content tool to read the content from the PDF file located at "/content/Understanding_Climate_Change.pdf".',
    agent=pdf_reader,
    expected_output="The full, raw text extracted from the PDF file, which will be passed to the writer."
)

task_article_drafting = Task(
    description="Based on the text provided from the PDF, write a comprehensive article of 8-10 paragraphs.",
    agent=article_writer,
    expected_output="A well-structured article with 8 to 10 paragraphs summarizing the key points from the text.",
    context=[task_read_pdf]
)

task_title_generation = Task(
    description="Generate an engaging title of about 5-7 words for the article you just read.",
    agent=title_creator,
    expected_output="A single, compelling title for the article.",
    context=[task_article_drafting]
)

# ----------------- 5. إنشاء وتجميع الطاقم (Crew) -----------------

crew = Crew(
    agents=[pdf_reader, article_writer, title_creator],
    tasks=[task_read_pdf, task_article_drafting, task_title_generation],
    verbose=True,
    process=Process.sequential
)

# ----------------- 6. بدء تشغيل الطاقم -----------------
print("🚀 Starting Crew Execution with a more capable model...")
result = crew.kickoff()

print("\n\n✅ Crew Execution Finished!")
print("Final Result:")
print(result)